// lib/features/expense/data/export_service.dart

import 'dart:io';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:expense/features/expense/domain/model/expense.dart';
import 'package:expense/core/extensions.dart';
import 'package:printing/printing.dart'; // for PdfGoogleFonts

class ExportService {
  /// Generates a PDF and returns the file path
  Future<String> generatePDF({
    required List<Expense> expenses,
    required DateTime from,
    required DateTime to,
  }) async {
  final baseFont = await PdfGoogleFonts.notoSansRegular();
final boldFont = await PdfGoogleFonts.notoSansBold();
    final pdf = pw.Document();


    // Filter by date range
    final filtered = expenses
        .where((e) =>
            e.date.isAfter(from.subtract(const Duration(days: 1))) &&
            e.date.isBefore(to.add(const Duration(days: 1))))
        .toList()
      ..sort((a, b) => b.date.compareTo(a.date));

    final total = filtered.fold(0.0, (sum, e) => sum + e.amount);
    final dateFormat = DateFormat('dd MMM yyyy');
    final rangeStr =
        '${dateFormat.format(from)} — ${dateFormat.format(to)}';

    // Category breakdown
    final Map<String, double> catTotals = {};
    for (final e in filtered) {
      final cat =
          e.category.name[0].toUpperCase() + e.category.name.substring(1);
      catTotals[cat] = (catTotals[cat] ?? 0) + e.amount;
    }

    final theme = pw.ThemeData.withFont(
  base: baseFont,
  bold: boldFont,
);


    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        theme: theme,
        margin: const pw.EdgeInsets.all(32),
        header: (context) => _buildHeader(rangeStr),
        footer: (context) => _buildFooter(context),
        build: (context) => [
          // ── Summary card ──
          _buildSummarySection(
            total: total,
            count: filtered.length,
            from: from,
            to: to,
          ),
          pw.SizedBox(height: 20),

          // ── Category breakdown ──
          if (catTotals.isNotEmpty) ...[
            _buildSectionTitle('Spending by Category'),
            pw.SizedBox(height: 8),
            _buildCategoryTable(catTotals, total),
            pw.SizedBox(height: 20),
          ],

          // ── Expense list ──
          _buildSectionTitle('Expense Details'),
          pw.SizedBox(height: 8),

          if (filtered.isEmpty)
            pw.Center(
              child: pw.Text('No expenses in this date range.',
                  style: pw.TextStyle(
                      color: PdfColors.grey,
                      fontStyle: pw.FontStyle.italic)),
            )
          else
            _buildExpenseTable(filtered),
        ],
      ),
    );

    // Save to temp directory
    final dir = await getTemporaryDirectory();
    final fileName =
        'expenses_${DateFormat('yyyyMMdd').format(from)}_${DateFormat('yyyyMMdd').format(to)}.pdf';
    final file = File('${dir.path}/$fileName');
    await file.writeAsBytes(await pdf.save());
    return file.path;
  }

  // ── PDF Header ──
  pw.Widget _buildHeader(String rangeStr) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 12),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          bottom: pw.BorderSide(color: PdfColors.deepPurple, width: 2),
        ),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Expense Report',
            style: pw.TextStyle(
              fontSize: 20,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.deepPurple,
            ),
          ),
          pw.Text(
            rangeStr,
            style: pw.TextStyle(fontSize: 11, color: PdfColors.grey700),
          ),
        ],
      ),
    );
  }

  // ── PDF Footer ──
  pw.Widget _buildFooter(pw.Context context) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 8),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
            top: pw.BorderSide(color: PdfColors.grey300, width: 1)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text('Generated by Expense Tracker',
              style:
                  pw.TextStyle(fontSize: 9, color: PdfColors.grey)),
          pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: pw.TextStyle(fontSize: 9, color: PdfColors.grey),
          ),
        ],
      ),
    );
  }

  // ── Summary Section ──
  pw.Widget _buildSummarySection({
    required double total,
    required int count,
    required DateTime from,
    required DateTime to,
  }) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: PdfColors.deepPurple50,
        borderRadius: pw.BorderRadius.circular(8),
        border: pw.Border.all(color: PdfColors.deepPurple200),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
        children: [
          _summaryItem('Total Spent', total.toCurrency()),
          _summaryItem('Transactions', '$count'),
          _summaryItem('Days',
              '${to.difference(from).inDays + 1}'),
        ],
      ),
    );
  }

  pw.Widget _summaryItem(String label, String value) {
    return pw.Column(
      children: [
        pw.Text(value,
            style: pw.TextStyle(
                fontSize: 16,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.deepPurple)),
        pw.SizedBox(height: 4),
        pw.Text(label,
            style:
                pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
      ],
    );
  }

  // ── Section Title ──
  pw.Widget _buildSectionTitle(String title) {
    return pw.Text(
      title,
      style: pw.TextStyle(
        fontSize: 13,
        fontWeight: pw.FontWeight.bold,
        color: PdfColors.deepPurple,
      ),
    );
  }

  // ── Category Table ──
  pw.Widget _buildCategoryTable(
      Map<String, double> catTotals, double total) {
    final sorted = catTotals.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));

    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
      columnWidths: {
        0: const pw.FlexColumnWidth(2),
        1: const pw.FlexColumnWidth(2),
        2: const pw.FlexColumnWidth(1),
      },
      children: [
        // Header row
        pw.TableRow(
          decoration:
              const pw.BoxDecoration(color: PdfColors.deepPurple100),
          children: ['Category', 'Amount', '%']
              .map((h) => pw.Padding(
                    padding: const pw.EdgeInsets.all(8),
                    child: pw.Text(h,
                        style: pw.TextStyle(
                            fontWeight: pw.FontWeight.bold,
                            fontSize: 10)),
                  ))
              .toList(),
        ),
        // Data rows
        ...sorted.map((entry) {
          final pct = (entry.value / total * 100).toStringAsFixed(1);
          return pw.TableRow(
            children: [
              _tableCell(entry.key),
              _tableCell(entry.value.toCurrency()),
              _tableCell('$pct%'),
            ],
          );
        }),
      ],
    );
  }

  // ── Expense Table ──
  pw.Widget _buildExpenseTable(List<Expense> expenses) {
    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
      columnWidths: {
        0: const pw.FixedColumnWidth(70),
        1: const pw.FlexColumnWidth(2),
        2: const pw.FlexColumnWidth(2),
        3: const pw.FlexColumnWidth(1.5),
        4: const pw.FlexColumnWidth(1.5),
      },
      children: [
        // Header
        pw.TableRow(
          decoration:
              const pw.BoxDecoration(color: PdfColors.deepPurple100),
          children: ['Date', 'Title', 'Description', 'Category', 'Amount']
              .map((h) => pw.Padding(
                    padding: const pw.EdgeInsets.all(8),
                    child: pw.Text(h,
                        style: pw.TextStyle(
                            fontWeight: pw.FontWeight.bold,
                            fontSize: 9)),
                  ))
              .toList(),
        ),
        // Rows
        ...expenses.asMap().entries.map((entry) {
          final i = entry.key;
          final e = entry.value;
          final bg = i % 2 == 0 ? PdfColors.white : PdfColors.grey100;
          final cat =
              e.category.name[0].toUpperCase() + e.category.name.substring(1);
          return pw.TableRow(
            decoration: pw.BoxDecoration(color: bg),
            children: [
              _tableCell(DateFormat('dd MMM yy').format(e.date)),
              _tableCell(e.name),
              _tableCell(e.description.isEmpty ? '—' : e.description),
              _tableCell(cat),
              _tableCell(e.amount.toCurrency(),
                  bold: true, color: PdfColors.deepPurple),
            ],
          );
        }),
      ],
    );
  }

  pw.Widget _tableCell(String text,
      {bool bold = false, PdfColor? color}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(7),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 9,
          fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
          color: color,
        ),
      ),
    );
  }
}