// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfCCZJ5Sxxf6IrBo9_RapQZGk8xHWjHdU',
    appId: '1:1092078604126:web:1988450e82304688ca49cf',
    messagingSenderId: '1092078604126',
    projectId: 'fir-60a1c',
    authDomain: 'fir-60a1c.firebaseapp.com',
    storageBucket: 'fir-60a1c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzJOa1RrrQWLfD2VPMiOuTcuwcQmQywcg',
    appId: '1:1092078604126:android:185af3bf33205d74ca49cf',
    messagingSenderId: '1092078604126',
    projectId: 'fir-60a1c',
    storageBucket: 'fir-60a1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDbCe5xKxd0EC1nD1NrhsCWKHkb-vDK2I',
    appId: '1:1092078604126:ios:be52917a1cf6e8d0ca49cf',
    messagingSenderId: '1092078604126',
    projectId: 'fir-60a1c',
    storageBucket: 'fir-60a1c.firebasestorage.app',
    iosBundleId: 'com.example.expense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDbCe5xKxd0EC1nD1NrhsCWKHkb-vDK2I',
    appId: '1:1092078604126:ios:be52917a1cf6e8d0ca49cf',
    messagingSenderId: '1092078604126',
    projectId: 'fir-60a1c',
    storageBucket: 'fir-60a1c.firebasestorage.app',
    iosBundleId: 'com.example.expense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfCCZJ5Sxxf6IrBo9_RapQZGk8xHWjHdU',
    appId: '1:1092078604126:web:e20f8c46f6bcc534ca49cf',
    messagingSenderId: '1092078604126',
    projectId: 'fir-60a1c',
    authDomain: 'fir-60a1c.firebaseapp.com',
    storageBucket: 'fir-60a1c.firebasestorage.app',
  );
}
